# Generated by rust2rpm 28
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%global crate blob-wrangler

Name:           rust-blob-wrangler
Version:        0.0.1
Release:        %autorelease
Summary:        Extract firmware from Android vendor partitions

License:        MIT AND BSD-3-Clause
URL:            https://crates.io/crates/blob-wrangler
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  systemd-rpm-macros

%global _description %{expand:
Extract firmware from Android vendor partitions.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# Apache-2.0 OR MIT
# MIT
# MIT AND BSD-3-Clause
# MIT OR Apache-2.0
# Unlicense OR MIT
License:        MIT AND BSD-3-Clause AND (MIT OR Apache-2.0) AND (Unlicense OR MIT)
# LICENSE.dependencies contains a full license breakdown

%{?systemd_ordering}
Requires:       kmod

%post
%systemd_post blob-wrangler.service

%preun
%systemd_preun blob-wrangler.service

%postun
%systemd_postun_with_restart blob-wrangler.service

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.BSD-3-Clause
%license LICENSE.dependencies
%doc README.md
%doc configs/README.md
%{_bindir}/blob-wrangler
%{_unitdir}/blob-wrangler.service
%dir %{_datadir}/blob-wrangler
%{_datadir}/blob-wrangler/configs
%dir %{_sysconfdir}/blob-wrangler
%dir %{_sharedstatedir}/blob-wrangler
%dir %{_sharedstatedir}/blob-wrangler/mounts

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
install -Dpm0644 blob-wrangler.service %{buildroot}%{_unitdir}/blob-wrangler.service
install -dm0755 %{buildroot}%{_datadir}/blob-wrangler/configs
install -pm0644 configs/*.toml %{buildroot}%{_datadir}/blob-wrangler/configs/
install -dm0755 %{buildroot}%{_sysconfdir}/blob-wrangler %{buildroot}%{_sharedstatedir}/blob-wrangler/mounts

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
