[wrangler]
dynpart = "system"
firmware = [
    { partition = "vendor", origin = "firmware", destination = "qcom/sdm845/pixel3", kernel = { lt = "7.0" }, files = [
            { name = "a630_zap.mdt", required = true },
            { name = "adsp.mdt", required = true },
            { name = "adspr.jsn" },
            { name = "adspua.jsn" },
            { name = "cdsp.mdt", required = true },
            { name = "cdspr.jsn" },
            { name = "ipa_fws.mdt", required = true },
            { name = "modemuw.jsn" },
            { name = "slpi.mdt" },
            { name = "venus.mdt", required = true },
            { name = "wlanmdsp.mbn" },
        ] },
    { partition = "vendor", origin = "firmware", destination = "qcom/sdm845/Google/blueline", kernel = { gte = "7.0" }, files = [
            { name = "a630_zap.mdt", required = true },
            { name = "adsp.mdt", required = true },
            { name = "adspr.jsn" },
            { name = "adspua.jsn" },
            { name = "cdsp.mdt", required = true },
            { name = "cdspr.jsn" },
            { name = "ipa_fws.mdt", required = true },
            { name = "modemuw.jsn" },
            { name = "slpi.mdt" },
            { name = "venus.mdt", required = true },
            { name = "wlanmdsp.mbn" },
        ] },
    { partition = "vendor", origin = "firmware", destination = "qca/pixel3", kernel = { lt = "7.0" }, files = [
            { name = "crnv21.bin", required = true },
        ] },
    { partition = "vendor", origin = "firmware", destination = "qca", kernel = { gte = "7.0" }, files = [
            { name = "crnv21.bin", required = true },
        ] },
    { partition = "vendor", origin = "firmware", destination = "qca", files = [
            { name = "crbtfw21.tlv", required = true },
        ] },
    { partition = "modem", origin = "image", destination = "qcom/sdm845/pixel3", kernel = { lt = "7.0" }, files = [
            { name = "mba.mbn", required = true },
            { name = "modem.mdt", required = true },
            { name = "modemr.jsn" },
        ] },
    { partition = "modem", origin = "image", destination = "qcom/sdm845/Google/blueline", kernel = { gte = "7.0" }, files = [
            { name = "mba.mbn", required = true },
            { name = "modem.mdt", required = true },
            { name = "modemr.jsn" },
        ] },
]
