[wrangler]
dynpart = "super"
firmware = [
    { partition = "vendor", origin = "firmware", destination = "qcom/qcm6490/SHIFT/otter", files = [
            { name = "a660_zap.mdt" },
# This line causes blob-wrangler to fail, re-enable once the issue is fixed
#            { name = "vpu20_1v.mdt", rename = "venus.mdt" },
            { name = "yupik_ipa_fws.mdt", rename = "ipa_fws.mdt" },
        ] },
    { partition = "modem", origin = "image", destination = "qcom/qcm6490/SHIFT/otter", files = [
            { name = "adsp.mdt" },
            { name = "adspr.jsn" },
            { name = "adsps.jsn" },
            { name = "adspua.jsn" },
            { name = "battmgr.jsn" },
            { name = "cdsp.mdt" },
            { name = "cdspr.jsn" },
            { name = "modem.mdt" },
            { name = "modemr.jsn" },
            { name = "wpss.mdt" },
        ] },
    { partition = "bluetooth", origin = "image", destination = "qca", files = [
            { name = "msbtfw11.mbn" },
            { name = "msnv11.bin" },
        ] },
]
