[juicer]
firmware = [
    { partition = "vendor", origin = "firmware", destination = "qcom/sdm845/beryllium", files = [
            "a630_zap.mdt",
            "ipa_fws.mdt",
        ] },
    { partition = "vendor", origin = "firmware", destination = "", files = [
            "tas2559_uCDSP.bin",
        ] },
    { partition = "modem", origin = "image", destination = "qcom/sdm845/beryllium", files = [
            "adsp.mdt",
            "adspr.jsn",
            "adspua.jsn",
            "cdsp.mdt",
            "cdspr.jsn",
            "mba.mbn",
            "modem.mdt",
            "modemr.jsn",
            "modemuw.jsn",
            "slpi.mdt",
            "slpir.jsn",
            "slpius.jsn",
            "venus.mdt",
            "wlanmdsp.mbn",
        ] },
    { partition = "bluetooth", origin = "image", destination = "qca/beryllium", files = [
            "crnv21.bin",
        ] },
    { partition = "bluetooth", origin = "image", destination = "qca", files = [
            "crbtfw21.tlv",
        ] },
]
